# Generated by Django 4.0.4 on 2023-02-11 19:30

from django.db import migrations
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "user_fixture.json")


def reverse_load_fixtures(state, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_load_fixtures)
    ]
